import { Movie } from '../types/movie'

export const mockMovies: Movie[] = [
  {
    id: 1,
    title: 'The Shawshank Redemption',
    description: 'Dos hombres encarcelados forjan una amistad a lo largo de los años, encontrando consuelo y eventual redención a través de actos de decencia.',
    poster: '',
    backdrop: '',
    releaseDate: '1994-10-14',
    rating: 9.3,
    genre: ['Drama', 'Crime'],
    duration: 142,
    director: 'Frank Darabont',
    cast: ['Tim Robbins', 'Morgan Freeman'],
  },
  {
    id: 2,
    title: 'The Godfather',
    description: 'El patriarca de una dinastía del crimen organizado transfiere el control de su imperio clandestino a su hijo menor y reticente.',
    poster: '',
    backdrop: '',
    releaseDate: '1972-03-24',
    rating: 9.2,
    genre: ['Drama', 'Crime'],
    duration: 175,
    director: 'Francis Ford Coppola',
    cast: ['Marlon Brando', 'Al Pacino'],
  },
  {
    id: 3,
    title: 'The Dark Knight',
    description: 'Cuando la amenaza conocida como el Joker siembra el caos en Gotham, Batman debe afrontar una de sus pruebas más grandes para combatir la injusticia.',
    poster: '',
    backdrop: '',
    releaseDate: '2008-07-18',
    rating: 9.0,
    genre: ['Action', 'Crime', 'Drama'],
    duration: 152,
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Heath Ledger'],
  },
  {
    id: 4,
    title: 'Pulp Fiction',
    description: 'Las vidas de dos sicarios, un boxeador, un gánster y su esposa se entrelazan en cuatro relatos de violencia y redención.',
    poster: '',
    backdrop: '',
    releaseDate: '1994-10-14',
    rating: 8.9,
    genre: ['Drama', 'Crime'],
    duration: 154,
    director: 'Quentin Tarantino',
    cast: ['John Travolta', 'Samuel L. Jackson'],
  },
  {
    id: 5,
    title: 'Inception',
    description: 'Un ladrón que roba secretos corporativos mediante la tecnología de compartir sueños recibe la misión inversa: implantar una idea.',
    poster: '',
    backdrop: '',
    releaseDate: '2010-07-16',
    rating: 8.8,
    genre: ['Action', 'Sci-Fi', 'Thriller'],
    duration: 148,
    director: 'Christopher Nolan',
    cast: ['Leonardo DiCaprio', 'Marion Cotillard'],
  },
  {
    id: 6,
    title: 'Forrest Gump',
    description: 'Las presidencias de Kennedy y Johnson se desarrollan desde la perspectiva de un hombre de Alabama con un coeficiente intelectual de 75.',
    poster: '',
    backdrop: '',
    releaseDate: '1994-07-06',
    rating: 8.8,
    genre: ['Drama', 'Romance'],
    duration: 142,
    director: 'Robert Zemeckis',
    cast: ['Tom Hanks', 'Sally Field'],
  },
  {
    id: 7,
    title: 'The Matrix',
    description: 'Un programador informático descubre que la realidad que conoce es una simulación creada por máquinas inteligentes.',
    poster: '',
    backdrop: '',
    releaseDate: '1999-03-31',
    rating: 8.7,
    genre: ['Action', 'Sci-Fi', 'Thriller'],
    duration: 136,
    director: 'Lana Wachowski',
    cast: ['Keanu Reeves', 'Laurence Fishburne'],
  },
  {
    id: 8,
    title: 'Interstellar',
    description: 'Un equipo de exploradores viaja a través de un agujero de gusano en el espacio para asegurar la supervivencia de la humanidad.',
    poster: '',
    backdrop: '',
    releaseDate: '2014-11-07',
    rating: 8.6,
    genre: ['Adventure', 'Drama', 'Sci-Fi'],
    duration: 169,
    director: 'Christopher Nolan',
    cast: ['Matthew McConaughey', 'Anne Hathaway'],
  },
]
